export const BASE_PATH = process.env.NEXT_PUBLIC_BASE_PATH || ''
export const RESEND_API_KEY = process.env.RESEND_API_KEY || ''
export const FIREBASE_ADMIN_PROJECT_ID = process.env.FIREBASE_ADMIN_PROJECT_ID || ''
export const FIREBASE_ADMIN_PRIVATE_KEY = process.env.FIREBASE_ADMIN_PRIVATE_KEY || ''
export const FIREBASE_ADMIN_CLIENT_EMAIL = process.env.FIREBASE_ADMIN_CLIENT_EMAIL || ''
